accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
]

project_7/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ]+urlpatterns

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=100, default="")
	last_name = models.CharField(max_length=100, default="")
	email = models.EmailField(default="")
	birthday = models.DateField(null=True, blank=True)
	bio = models.TextField(default="")
	avatar = models.ImageField(null=True, blank=True,upload_to='./user_profile_avatar')

	

accounts/forms.py
from django import forms
from . import models

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = models.UserProfile
		exclude = ['user']

	def __init__(self, *args, **kwargs):
	    super(UserProfileForm, self).__init__(*args, **kwargs)
	    self.fields['avatar'].required = False


class ChangePasswordForm(forms.Form):
	old_password = forms.CharField()
	new_password = forms.CharField()
	confirm_new_password = forms.CharField()

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from . import models
from . import forms
from django.contrib.auth.models import User


def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    # go to view profile if signing in
                    return HttpResponseRedirect(reverse('accounts:view_profile'))  # TODO: go to profile
                    
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            messages.success(
                request,
                "You're now a user! You've been signed in, too."
            )
            # go to edit profile if you just signed up to fill out information
            return HttpResponseRedirect(reverse('accounts:view_profile'))
    return render(request, 'accounts/sign_up.html', {'form': form})

@login_required
def view_profile(request):    
    try:
        userprofile = models.UserProfile.objects.get(user=request.user)
    except ObjectDoesNotExist:
        userprofile = models.UserProfile()
        userprofile.user = request.user
        userprofile.save()

    return render(request, 'accounts/view_profile.html', {"userprofile": userprofile})
    
@login_required
def edit_profile(request):
    try:
        userprofile = models.UserProfile.objects.get(user=request.user)
    except ObjectDoesNotExist:
        userprofile = models.UserProfile()
        userprofile.user = request.user
        userprofile.save()

    if request.method == "POST":
        form = forms.UserProfileForm(request.POST, request.FILES, instance=userprofile)        
        if form.is_valid():
                     
            form.save()
            return HttpResponseRedirect(reverse('accounts:view_profile'))
    else:
        form = forms.UserProfileForm(instance=userprofile)

        return render(request, 'accounts/edit_profile.html', {"userprofileform": form})
    


def sign_out(request):
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))

project_7/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

accounts/templates/accounts/edit_profile.html
{% extends "layout.html" %}

{% block title %}Edit Profile | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	{{ userprofileform.as_p }}
	<input type="submit">
</form>
{% endblock %}

accounts/templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_up' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign Up">
</form>
{% endblock %}

accounts/templates/accounts/view_profile.html
{% extends "layout.html" %}

{% block title %}View Profile | {{ super }}{% endblock %}

{% block body %}
<div class="profile-container">
	<p>
	 {{userprofile.first_name}} {{userprofile.last_name}}</p>
	
	
		

		{% if userprofile.avatar %}
			<img class="profile-image" src="{{userprofile.avatar.url}}" alt="Profile Avatar">
		{% endif %}
	

	
	
	
		<p>Email: {{userprofile.email}}</p>
		
		<p>Birthday: {{userprofile.birthday}}</p>
		<p>Bio: {{userprofile.bio}}</p>
	
</div>	
{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% block body %}
    <div class="grid-25">
        nav here maybe?
    </div>
    <div class="grid-75">
        <h1>Welcome!</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad amet assumenda beatae blanditiis, deserunt doloremque ea earum excepturi id, impedit ipsam magnam nulla obcaecati, quidem quis soluta tenetur vitae?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad amet assumenda beatae blanditiis, deserunt doloremque ea earum excepturi id, impedit ipsam magnam nulla obcaecati, quidem quis soluta tenetur vitae?</p>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}">

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>


</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        <li><a href="#">nav</a></li>
                        <li><a href="#">here?</a></li>
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign
                                In</a></li>
                        {% else %}
                            <li><a href={% url 'accounts:view_profile' %}>View Profile</a></li>
                            <li><a href={% url 'accounts:edit_profile' %}>Edit Profile</a></li>
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>